### ISSUE TITLE
Fix merge sarif task

### ISSUE THREAD

**Issue by rock3r** [JetBrains/jewel#573]
For some reason stopped working in #571...

```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':mergeSarifReports'.
// ...
Caused by: java.lang.NoSuchMethodError: 'void io.github.detekt.sarif4k.ToolComponent.<init>(io.github.detekt.sarif4k.ToolComponentReference, java.util.List, java.lang.String, java.lang.String, io.github.detekt.sarif4k.MultiformatMessageString, java.lang.String, java.util.Map, java.lang.String, java.lang.String, java.lang.Boolean, java.lang.String, java.lang.String, java.util.List, java.lang.String, java.lang.String, java.util.List, java.lang.String, java.lang.String, java.lang.String, io.github.detekt.sarif4k.PropertyBag, java.lang.String, java.util.List, java.lang.String, io.github.detekt.sarif4k.MultiformatMessageString, java.util.List, java.util.List, io.github.detekt.sarif4k.TranslationMetadata, java.lang.String, int, kotlin.jvm.internal.DefaultConstructorMarker)'
	at MergeSarifTask$merge$merged$6.invoke(MergeSarifTask.kt:53)
	at MergeSarifTask$merge$merged$6.invoke(MergeSarifTask.kt:50)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:811)
	at MergeSarifTask.merge(MergeSarifTask.kt:56)
// ...
```
